# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/423f0379-7c43-4e9b-beba-15aaa6e3c867";
      fsType = "btrfs";
      options = [ "subvol=@nixos-root" "compress=zstd" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/423f0379-7c43-4e9b-beba-15aaa6e3c867";
      fsType = "btrfs";
      options = [ "subvol=@nixos-nix" "compress=zstd" "noatime" ];
    };

  fileSystems."/home/era" =
    { device = "/dev/disk/by-uuid/423f0379-7c43-4e9b-beba-15aaa6e3c867";
      fsType = "btrfs";
      options = [ "subvol=@era-home" "compress=zstd" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F1FB-58C6";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];
  zramSwap.enable = true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
